title:              Kuat Telegenov
email:              ktelegenov@gmail.com
description:        Kuat Telegenov's personal website
author:             Kuat Telegenov
baseurl:            ""
url:                "https://ktelegenov.github.io"

# Social Profiles
twitter_username:   ktelegenov
github_username:    ktelegenov
facebook_username:  ktelegenov
instagram_username: kuat.telegenov
linkedin_username: ktelegenov

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
